#! /usr/bin/env/ python3
from itertools import permutations
def biggerIsGreater(w):
    p = permutations(w,len(w))
    it = next(p, None)
#    it = p.next()
    it = next(p, None)
    if (it == None):
        return None
    else:
        print(p)
        return list(it)
print(''.join(biggerIsGreater('dkhc')))
print(permutations('ABCD', 2))

