#! /usr/bin/env/ python3
from itertools import permutations
def biggerIsGreater(w):
    p = permutations(w,len(w))
    it = next(p, None)
#    it = p.next()
    it = next(p, None)
    it = next(p, None)

    return list(it)
print(biggerIsGreater('bb'))
